const path = require("path");
const CopyWebpackPlugin = require("copy-webpack-plugin");

module.exports = {
  mode: 'development',
  entry: "./src/main.js",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist"),
  },
  plugins: [
    new CopyWebpackPlugin([{ from: "./src/index.html", to: "index.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/homepage.html", to: "homepage.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/Blog1.html", to: "Blog1.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/Blog2.html", to: "Blog2.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/Blog3.html", to: "Blog3.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/awareness.html", to: "awareness.html" }]),
    // new CopyWebpackPlugin([{ from: "./src/html/donorsignup.html", to: "donorsignup.html" }]),
    //new CopyWebpackPlugin([{ from: "./src/html/donorlogin.html", to: "donorlogin.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/donor-registration.html", to: "donor-registration.html" }]),
    // new CopyWebpackPlugin([{ from: "./src/html/hospitallogin.html", to: "hospitallogin.html" }]),
    // new CopyWebpackPlugin([{ from: "./src/html/hospitalsignup.html", to: "hospitalsignup.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/donor-pledge.html", to: "donor-pledge.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/patient-registration.html", to: "patient-registration.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/verify-pledges.html", to: "verify-pledges.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/view-donors.html", to: "view-donors.html" }]),
    // new CopyWebpackPlugin([{ from: "./src/html/view-pledges.html", to: "view-pledges.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/view-patients.html", to: "view-patients.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/transplant-matching.html", to: "transplant-matching.html" }]),
    new CopyWebpackPlugin([{ from: "./src/css/bootstrap.css", to: "css/bootstrap.css" }]),
    new CopyWebpackPlugin([{ from: "./src/css/styles.css", to: "css/styles.css" }]),
    new CopyWebpackPlugin([{ from: "./src/css/style-home.css", to: "css/style-home.css" }]),
    new CopyWebpackPlugin([{ from: "./src/css/style-blog.css", to: "css/style-blog.css" }]),
    new CopyWebpackPlugin([{ from: "./src/css/nucleo-icons.css", to: "css/nucleo-icons.css" }]),
    new CopyWebpackPlugin([{ from: "./src/css/nucleo-svg.css", to: "css/nucleo-svg.css" }]),
    new CopyWebpackPlugin([{ from: "./src/css/argon-dashboard.css", to: "css/argon-dashboard.css" }]),
    new CopyWebpackPlugin([{ from: "./src/css/argon-dashboard.css.map", to: "css/argon-dashboard.css.map" }]),
    new CopyWebpackPlugin([{ from: "./src/css/argon-dashboard.min.css", to: "css/argon-dashboard.min.css" }]),
    new CopyWebpackPlugin([{ from: "./src/css/fontawesome-all.css", to: "css/fontawesome-all.css" }]),
    new CopyWebpackPlugin([{ from: "./src/js/jquery.counterup.min.js", to: "js/jquery.counterup.min.js" }]),
    new CopyWebpackPlugin([{ from: "./src/js/argon-dashboard.js", to: "js/argon-dashboard.js" }]),
    new CopyWebpackPlugin([{ from: "./src/js/argon-dashboard.min.js", to: "js/argon-dashboard.min.js" }]),
    new CopyWebpackPlugin([{ from: "./src/js/plugins/bootstrap-notify.js", to: "js/plugins/bootstrap-notify.js" }]),
    new CopyWebpackPlugin([{ from: "./src/js/plugins/Chart.extension.js", to: "js/plugins/Chart.extension.js" }]),
    new CopyWebpackPlugin([{ from: "./src/js/plugins/chartjs.min.js", to: "js/plugins/chartjs.min.js" }]),
    new CopyWebpackPlugin([{ from: "./src/js/plugins/perfect-scrollbar.min.js", to: "js/plugins/perfect-scrollbar.min.js" }]),
    new CopyWebpackPlugin([{ from: "./src/js/plugins/smooth-scrollbar.min.js", to: "js/plugins/smooth-scrollbar.min.js" }]),
    new CopyWebpackPlugin([{ from: "./src/js/core/popper.min.js", to: "js/core/popper.min.js" }]),
    new CopyWebpackPlugin([{ from: "./src/js/core/bootstrap.min.js", to: "js/core/bootstrap.min.js" }]),
    new CopyWebpackPlugin([{ from: "./src/js/core/bootstrap.bundle.min.js", to: "js/core/bootstrap.bundle.min.js" }]),
    new CopyWebpackPlugin([{ from: "./src/scss/argon-dashboard.scss", to: "scss/argon-dashboard.scss" }]),
    new CopyWebpackPlugin([{ from: "./src/images/blog1.jpeg", to: "images/blog1.jpeg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/blog2.jpeg", to: "images/blog2.jpeg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/blog3.jpeg", to: "images/blog3.jpeg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Hertfelt1.jpg", to: "images/Hertfelt1.jpg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Heartelt2.png", to: "images/Heartelt2.png" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Heartelt3.png", to: "images/Heartelt3.png" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Heartelt4.png", to: "images/Heartelt4.png" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Heartfelt5.png", to: "images/Heartfelt5.png" }]),
    new CopyWebpackPlugin([{ from: "./src/images/organ-donations.webp", to: "images/organ-donations.webp" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Picture1.jpg", to: "images/Picture1.jpg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Picture2.jpg", to: "images/Picture2.jpg"}]),
    new CopyWebpackPlugin([{ from: "./src/images/Pooja-Bijarnia.jpg", to: "images/Pooja-Bijarnia.jpg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Pooja-Bijarnia-1.jpg", to: "images/Pooja-Bijarnia-1.jpg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Pooja-Bijarnia-2.jpg", to: "images/Pooja-Bijarnia-2.jpg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Pooja-Bijarnia-3.jpg", to: "images/Pooja-Bijarnia-3.jpg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Pooja-Bijarnia-4.jpg", to: "images/Pooja-Bijarnia-4.jpg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Pooja-Bijarnia-5.jpg", to: "images/Pooja-Bijarnia-5.jpg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/premium_photo-1702598804759-8fb687f774fb.avif", to: "images/premium_photo-1702598804759-8fb687f774fb.avif" }]),
    new CopyWebpackPlugin([{ from: "./src/images/sister-to-mother.jpg", to: "images/sister-to-mother.jpg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/sister-to-mother1.jpg", to: "images/sister-to-mother1.jpg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/sister-to-mother2.jpg", to: "images/sister-to-mother2.jpg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/sister-to-mother3.jpg", to: "images/sister-to-mother3.jpg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/sister-to-mother4.jpg", to: "images/sister-to-mother4.jpg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/sister-to-mother5.jpg", to: "images/sister-to-mother5.jpg" }]), 
    new CopyWebpackPlugin([{ from: "./src/images/OH-logo-removebg-preview.png", to: "images/OH-logo-removebg-preview.png" }]),
    new CopyWebpackPlugin([{ from: "./src/images/favicon_-removebg-preview.png", to: "images/favicon_-removebg-preview.png" }]),
    new CopyWebpackPlugin([{ from: "./src/images/DLC-Media-myth-fact-FB-IG.png", to: "images/DLC-Media-myth-fact-FB-IG.png" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Indian-Organ-Donation-Day.webp", to: "images/Indian-Organ-Donation-Day.webp" }]),
    new CopyWebpackPlugin([{ from: "./src/images/organdonate.webp", to: "images/organdonate.webp" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Organ-donation-liver.png", to: "images/Organ-donation-liver.png" }]),
    new CopyWebpackPlugin([{ from: "./src/images/stats.png", to: "images/stats.png"}]),
    new CopyWebpackPlugin([{ from: "./src/images/which-organs-can-be-donated.png", to: "images/which-organs-can-be-donated.png" }]),
  ],
  devServer: { contentBase: path.join(__dirname, "dist"), compress: true },
};